rgst-io/stencil

- .gitignore
- cmd/stencil/create_module.go
- internal/codegen/stencil_test.go
- internal/codegen/testdata/module-hook/m1.tpl
- internal/codegen/tpl.go
- internal/codegen/tpl_file.go
- internal/codegen/tpl_stencil.go
- internal/codegen/tpl_stencil_test.go
* Template base url was wrong in the module creation (left over from outreach days)
* If you return 0 files in rendering your template, then stencil panics -- fixed
* Updated the file template renders to not need the $_ = hack by just returning empty string as the output
* Added launch.json to gitignore for local debugging
> fix: Template base URL, Panics, and nil func returns

- docs/reference/template-module.md
- internal/codegen/template.go
- internal/codegen/template_test.go
- internal/codegen/tpl.go
This commit adds support for special "library" templates that can never
generate files. The intent for these is to provide helper
functions/sub-templates for other templates to call. A libary template
is any template file that has the `.library.tpl` extension.
Adds tests ensuring that this functionality works as expected as well as
updates the documentation to reflect the introduction of them.
> feat: support library templates

- cmd/stencil/create_module.go
- cmd/stencil/create_module_test.go
Fixes #46 by way of removing most of the functionality in `create
module` for now, due to it being unclear what we'll carry over from the
existing template-base code. A future commit will improve this.
Adds a small test framework for testing commands which this adds a test
for `create module`.
> fix!(create module): only create stencil.yaml for now

- .vscode/schema.json
- internal/git/git.go
- internal/modules/resolver/resolver.go
- internal/modules/resolver/resolver_test.go
- stencil.yaml
Adds a module resolver library for the purposes of replacing the current
version resolver used by the `modules` package. This does not hook it up
yet, but provides us a scalable foundation for resolving versions.
Future PR(s) will change `stencil` to default to using versions found in
the lockfile, as well as adding a `stencil upgrade` command to upgrade
them.
The underlying resolver introduced in this PR supports simple constraint
functionality to allow flexibility in its usage in `stencil`, but there
is currently no plans to expose this functionality. Tests have been
added to ensure that the following behaviour is followed:
* If a criteria contains a branch, that branch should always be used.
* **Reason**: Branches cannot be compared and usually are being used
for testing purposes, so …
> refactor(modules): add module resolver

- cmd/stencil/upgrade_test.go
- internal/cmd/stencil/stencil.go
Changes in this PR allow `upgrade` command to add new modules if they do not exist in the lock file.
I'm aware that his might be not the expected behaviour of the command. So, please feel free to close the PR if the reported issue (#103) is not a valid one
> fix: allow upgrade cmd to install new modules

- internal/codegen/values.go
- internal/codegen/values_test.go
- internal/modules/module.go
The current box configuration implementation requires `gobox`, which
we're almost done removing from the dependency chain. As such, I'd like
to remove it.
My reasoning for doing so is that the current experience of `box`
creates gaps with open source repositories that are owned by an org,
causing those users to be unable to run `stencil` in those repositories,
normally resulting in an inability to build/run them.
I'd like to add box back later in another form, but for now it's best to
remove it and add it back later.
As far as I know, the current implementation also doesn't work in this
fork.
> refactor(box)!: remove box configuration

- .github/scripts/fury-upload.sh
- .github/workflows/release.yaml
- .goreleaser.yaml
We're going to use `fury.io` to host our packages so users don't have to
manually download a `deb`, `rpm`, `apk` file everytime.
> build: upload apt/rpm/apk packages to fury.io for publishing

- .github/workflows/release.yaml
This allows us to prove that archives created on releases were created
by a specific CI run.
> build: attest generated archives

- .editorconfig
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- .goreleaser.yaml
- .mise.toml
- .vscode/settings.json
- go.work.sum
- pkg/configuration/configuration.go
- schemas/stencil.jsonschema.json
- stencil.lock
- stencil.yaml
Uprades to the latest version of `stencil-golang` that supports most of
what we deviated from previously.
> build: use latest version of stencil-golang

- internal/codegen/tpl_file.go
- internal/codegen/tpl_file_test.go
> fix: file.Delete should delete lockfile history, if any exists

- .vscode/settings.json
- cmd/stencil/create.go
- cmd/stencil/create_module.go
- cmd/stencil/create_module_test.go
- cmd/stencil/lockfile_prune.go
- cmd/stencil/stencil.go
Instead of executing ourself, we use `NewStencilAction` and chain it
during `create module`. This should decrease the time to run tests, but
sadly we still need `chdir`, so we can't parallelize the tests (yet...)
> test: remove need to compile self

- docs/functions/stencil.ApplyTemplate.md
- internal/codegen/testdata/multi-file-input.tpl
- internal/codegen/tpl_stencil.go
- internal/codegen/tpl_stencil_test.go
- internal/codegen/values.go
- internal/modules/nativeext/apiv1/client.go
Data is moved from `.` to `.Data` to allow for passing parent template
values always. This also enables function recievers to always be passed
as well, in the case of having to do the `dict "Config" .Config` hack
that existed before.
> feat(codegen)!: ApplyTemplate data is on .Data

- .vscode/settings.json
- docs/reference/template-module.md
- internal/cmd/stencil/stencil_test.go
- internal/modules/module_test.go
- internal/modules/nativeext/caller.go
- internal/modules/nativeext/nativeext_test.go
- internal/modules/testdata/manifest.yaml
Removes most of the leftover `getoutreach` references left in test and other places.
Related to #1
> chore: remove getoutreach references in tests

- .golangci.yml
- .vscode/settings.json
- cmd/stencil/create_module.go
- cmd/stencil/create_module_test.go
- cmd/stencil/describe_test.go
- cmd/stencil/lockfile_prune.go
- cmd/stencil/stencil.go
- cmd/stencil/upgrade.go
- cmd/stencil/upgrade_test.go
- internal/codegen/values_test.go
- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
- pkg/configuration/testdata/tr-default/manifest.yaml
- pkg/configuration/type.go
- pkg/configuration/type_test.go
- schemas/manifest.jsonschema.json
Adds support for generating modules with a `manifest.yaml` as well as
populating `service.yaml` using `rgst-io/stencil-golang` in library
mode, unless specified to create a native extension.
stencil-golang in library mode has full CI, and is used mainly only for
releasing. Eventually, the release logic will be moved out and turned
into some framework (or use some other one) since it is a bit awkward to
depend on that for non-Go repositories.
> feat(create-module): use stencil-golang to create modules

- docs/funcs/module.Call.md
- internal/codegen/shared_state.go
- internal/codegen/tpl_module.go
- internal/codegen/tpl_module_test.go
The original design was to use the context of the caller in the functions being called, but after we tried to implement a function call this way realized that it was inverting ownership from usual function ownership.  The idea was to be able to use helper functions in the context of the caller, but the reality is that you want to pass in any needed context to the exported function, just like in standard programming.  This way the function owner can have "private" state/context inside the module that the function exposes a part of, per standard modules in general software engineering.
> fix: Cross-module calls should execute in the context of the callee

- go.mod
- go.sum
- go.work.sum
- internal/cmd/stencil/stencil.go
- pkg/configuration/configuration.go
- schemas/manifest.jsonschema.json
Allows enforcing a minimum stencil version for modules
Tested by taking a nested module and adding a min version, to make sure it cascades through nested modules properly, and forcing the stencil version to different things to verify the different behavior options.  Reorganizing the code to make this specific scenario unit testable looks like a fairly huge undertaking, so hoping we can bypass that.
> feat: Add MinStencilVersion parameter to module manifests

- internal/modules/module_test.go
- internal/modules/modules.go
Adds more details when the error is due to remotes being unable to be
found. This could be a credentials issue, so it's worth highlighting it
in the error message.
As part of this, I was reminded that we use `git` only for credentials
here, which should probably be switched to the token library in the
future. We don't do this right now since its hard to configure host git
on the fly to use the system-wide token, but it's worth considering to
unify token sources in the future.
> fix(modules): display more information on repo not found

- internal/modules/nativeext/nativeext.go
There's a potential race when writing to a file and attempting to
execute it immediately after on Linux. While this may not entirely be
the cause, it seems reasonable enough to attempt the workaround of
locking `syscall.ForkLock`.
> fix(nativeext):  text file busy

- internal/modules/nativeext/nativeext.go
Ensures that the cache directory exists before creating the extension
host. This fixes a case where locking could fail due to the cache
directory not existing yet.
> fix(nativeext): ensure cache dir exists

- pkg/configuration/configuration.go
- pkg/configuration/configuration_test.go
Removes the deprecated `NewManifest` and `NewDefaultManifest` functions.
These were replaced by their `Load` counterparts.
> fix(pkg/configuration)!: remove New*Manifest functions

- .goreleaser.yaml
- pkg/configuration/configuration.go
- schemas/manifest.jsonschema.json
- schemas/stencil.jsonschema.json
- tools/schemagen/go.mod
- tools/schemagen/go.sum
- tools/schemagen/schemagen.go
Once we changed to `v2`, we needed to also update the goreleaser
configuration to reflect the new import path, which was not done.
> fix(release): properly set versions after import path change

- internal/codegen/blocks.go
- internal/codegen/blocks_test.go
- internal/codegen/testdata/blocks-test.txt
- internal/codegen/tpl_stencil_test.go
Adds support for `-` in the name of a block.
> feat(blocks): allow hyphens in name

- .mise.toml
Upgrades us to Go 1.24 and all required dependencies to faciliate doing
so.
> feat(golang): upgrade to 1.24

- .gitattributes
- .github/workflows/linters.yaml
- .mise.lock
- .mise.toml
- go.work.sum
- internal/codegen/blocks.go
- internal/codegen/blocks_test.go
- internal/codegen/file.go
- internal/codegen/template_test.go
Deprecates V1 blocks by way of a persistent log message any time a v1
block is read from disk.
Adds support for `_` in block names.
> feat(blocks): support _ in block names and deprecate v1

- .github/workflows/release-after-merge.yaml
Allows easy chaining of releasing post merge of a PR.
> ci: add release-after-merge workflow

- cmd/stencil/describe.go
- cmd/stencil/upgrade.go
- cmd/stencil/upgrade_test.go
- internal/cmd/stencil/stencil.go
Some users want to re-run stencil all the time and not cherry-pick their
versions. We support this by always re-running stencil (a render) even
if there is no new versions of modules added.
The old behaviour can be kept with the new `-s` and
`--skip-render-no-changes` flag.
> feat(upgrade): re-render stencil templates even if no changes

- internal/codegen/tpl_stencil_arg.go
- internal/codegen/tpl_stencil_arg_test.go
Without this the top level requestor's manifest was used, which is
incorrect since it doesn't need to know of the dependencies of the
dependency it is using `from` for.
Also converted some `interface{}` -> `any`
> fix(arg): use recursive from's manifest context when resolving deps

- go.mod
- go.sum
- go.work.sum
- internal/codegen/functions.go
- internal/codegen/functions_test.go
This should allow less manual TOML serialization when generating files like `.mise.toml`.
For example, this is what the code change is in `rgst-io/stencil-golang`:
```diff
diff --git a/templates/.mise.toml.tpl b/templates/.mise.toml.tpl
index 641b830..680920b 100644
--- a/templates/.mise.toml.tpl
+++ b/templates/.mise.toml.tpl
@@ -16,12 +16,7 @@
[tools]
{{- range (fromYaml (stencil.Include "defaultVers")) }}
-{{- $key := index (keys .) 0 }}
-{{- $val := index . $key }}
-{{- if contains ":" $key }}
-{{- $key = quote $key }}
-{{- end }}
-{{ $key }} = "{{ $val }}"
+{{ . | toToml }}
{{- end }}
[tasks.build]
```
> feat(codegen): add functions to (de)serialize TOML

- go.mod
- go.sum
- internal/cmd/stencil/stencil.go
- internal/cmd/stencil/stencil_test.go
- internal/cmd/stencil/testdata/bad-min-stencil-version/manifest.yaml
- internal/cmd/stencil/testdata/both-stencil-versions/manifest.yaml
- internal/cmd/stencil/testdata/min-stencil-too-new/manifest.yaml
- internal/cmd/stencil/testdata/stencil-too-new/manifest.yaml
- internal/cmd/stencil/testdata/stencil-version-bad-constraint/manifest.yaml
- internal/cmd/stencil/testdata/stencil-version-matches-constraint/manifest.yaml
- internal/cmd/stencil/testdata/stencil-version-newer-than-min/manifest.yaml
- pkg/configuration/template_repository.go
- schemas/manifest.jsonschema.json
Allows Stencil modules to use semver constraints to specify what Stencil version is required to render it. This is basically a much more powerful version of `minStencilVersion`.
I intentionally prevent modules from specifying both `minStencilVersion` and `stencilVersion` as you can implement the former in the latter, but happy to discuss alternative ways of dealing with that.
We should also consider deprecating (obviously not removing) `minStencilVersion` in favor of this, although the code to implement it (and the basic tests that I added for it in this PR) is pretty small.
My original implementation had `StencilVersion` be a `*semver.Constraints` instead of a `string`, but that exposed the `Constraints` struct to the JSON schema.
> feat: add stencilVersion constraint to template repository manifest

- go.work.sum
- internal/codegen/stencil.go
- tools/schemagen/go.mod
Makes it so library templates are rendered before regular ones, but
still are shuffled.
> feat(codegen): render library templates before regular ones
